import Foundation
import XCTest

/// Step 4 of the ordered decision law — "same semantic owner ⇒ DIRECT" — is self-ratifying.
/// Its five conditions in **Terms** are satisfied by construction for any Swift shipping
/// inside the app bundle, so reclassifying a behaviour as DIRECT costs an author nothing and
/// the inventory grows without anyone deciding that it should.
///
/// This gate makes that growth a reviewed edit. It pins the inventory's entry count *and*
/// every entry's normalized size, because the measured drift is dominated by growth *inside*
/// an existing entry rather than by new bullets: `launcher surfaces and tab-context placement
/// (T-039, AIO-8)` went 1,571 → 2,727 characters between `fcac70d` and this change and
/// absorbed a further DIRECT behaviour under an unchanged heading. A count-only gate is blind
/// to that.
///
/// Neither assertion exercises judgment. Both are mechanical, so two reviewers applying them
/// reach the same answer — the standard the law sets for itself at
/// `docs/architecture-interaction-boundaries.md:30-31`.
final class DirectInventoryGateTests: XCTestCase {
    /// Lead phrase → normalized character length for every DIRECT inventory entry.
    ///
    /// Generated by running `directInventoryEntries()` against the document, not transcribed
    /// from a design. These entries predate the justification rule and are grandfathered by
    /// exact lead phrase and length; adding to this map is the reviewed act the gate exists
    /// to force, and removing from it is the direction the law wants.
    private static let pinnedEntries: [String: Int] = [
        "ordinary functions/modules inside one plugin generation": 56,
        "SwiftUI workspace, tab, pane, and settings interactions": 1313,
        "app lifecycle and composition-root wiring": 42,
        "install-channel routing": 946,
        "`WorkspaceStore` and typed workspace use cases": 47,
        "terminal and web surface pool retain/reconcile/focus/lifecycle": 63,
        "pane activity/attention state (T-029)": 510,
        "launcher surfaces and tab-context placement (T-039, AIO-8)": 2727,
        "personal runbooks (source-owned as `QuickCommand`)": 1384,
        "detected agent launch suggestions": 1207,
        "file-pane renderer selection (T-038)": 786,
        "a file cited in Agent Lens prose (T-068)": 785,
        "plugin-host administration from the Settings UI": 48,
        "Automation Canvas and Settings separation": 1869,
        "browser-surface renderer identity (T-077)": 1020,
        "pure parsers, ranking, schemas, and value transformations": 58,
        "`tenon.path.join/normalize/basename/dirname/extname`, implemented entirely inside the plugin runtime as pure string functions.": 126,
    ]

    func testDirectInventoryIsPinnedAgainstItsRecordedSize() throws {
        let law = try lawText()
        let entries = try directInventoryEntries()
        let pinned = Self.pinnedEntries
        let plugins = try shippedPluginCount()

        let declaredCount = try XCTUnwrap(
            Self.firstCapturedInteger(in: law, pattern: #"This inventory has (\d+) entries"#),
            """
            The interaction boundary law does not state the size of its DIRECT inventory, so \
            the inventory can grow without any reviewed edit to the law. Add the sentence \
            "This inventory has \(entries.count) entries, pinned in `DirectInventoryGateTests`." \
            to the DIRECT section under "#### Adding a DIRECT entry".
            """
        )

        XCTAssertEqual(
            entries.count,
            pinned.count,
            """
            The DIRECT inventory holds \(entries.count) entries against \(plugins) shipped \
            plugins; \(pinned.count) are pinned in this test. Every entry here is host Swift \
            that a plugin cannot reach.
            """
        )
        XCTAssertEqual(
            entries.count,
            declaredCount,
            """
            The DIRECT inventory holds \(entries.count) entries against \(plugins) shipped \
            plugins, but the law says it holds \(declaredCount). Update the sentence and this \
            test in the same reviewed change.
            """
        )

        let parsedLeads = Set(entries.map(\.lead))
        let pinnedLeads = Set(pinned.keys)
        let added = parsedLeads.subtracting(pinnedLeads).sorted()
        let removed = pinnedLeads.subtracting(parsedLeads).sorted()

        XCTAssertTrue(
            added.isEmpty,
            """
            New DIRECT inventory entries are not pinned in this test: \(added.joined(separator: " | ")). \
            Adding one is a reviewed classification decision: carry the labelled justification \
            clause required by "#### Adding a DIRECT entry", then pin the entry and its length here.
            """
        )
        // Disappearing is not a violation. The law pins these entries so they "can shrink
        // or disappear freely but cannot quietly grow" — reclassifying a behaviour out of
        // DIRECT into a CONTRIBUTION, EVENT, or INTENT is the direction this law wants, so
        // a gate that fails on removal would penalise exactly the movement it exists to
        // encourage. A stale key left in `pinned` costs nothing: it matches no entry and
        // gates nothing.
        _ = removed

        for entry in entries {
            guard let pinnedLength = pinned[entry.lead] else { continue }
            XCTAssertLessThanOrEqual(
                entry.length,
                pinnedLength,
                """
                DIRECT inventory entry grew — \(entry.lead): was \(pinnedLength), \
                now \(entry.length) characters. Enlarging an entry is the same act as adding \
                one; it is how this inventory actually grew. Carry the labelled justification \
                clause and update the pinned length here. Shrinking needs no update — the \
                pin is a ceiling, not an equality.
                """
            )
        }

        XCTAssertTrue(
            law.contains("#### Adding a DIRECT entry"),
            "The rule this gate enforces must stay written down in the law it guards."
        )
        XCTAssertTrue(
            law.contains("PluginViewModal"),
            """
            The refutation must stay in the law: `PluginViewModal` publishes a window-level \
            sheet across the plugin boundary and bundled kanban already uses it, so "no plugin \
            presentation surface existed" is refuted by shipped code and cannot be offered as \
            justification for a DIRECT entry.
            """
        )
    }

    func testEveryAddedOrEnlargedDirectEntryCarriesItsJustificationClause() throws {
        let entries = try directInventoryEntries()
        let pinned = Self.pinnedEntries

        for entry in entries {
            guard let reason = Self.justificationDebt(for: entry, against: pinned) else {
                continue
            }
            XCTAssertTrue(
                Self.carriesJustificationClause(entry),
                Self.unjustifiedMessage(entry: entry, reason: reason)
            )
        }
    }

    /// The test above iterates real data, and today every entry matches its pin — so its
    /// `guard` skips all seventeen and it reports green having never evaluated the rule. A
    /// check that has never once fired is not evidence that it fires. This exercises the
    /// same two predicates against synthetic entries, so the rule itself is under test
    /// rather than the current contents of the document.
    func testTheJustificationRuleRejectsAnUnjustifiedAdditionAndAcceptsAJustifiedOne() {
        let pinned = ["an existing behaviour": 40]
        let existing = DirectEntry(lead: "an existing behaviour", text: String(repeating: "x", count: 40))
        let grown = DirectEntry(lead: "an existing behaviour", text: String(repeating: "x", count: 80))
        let addedBare = DirectEntry(lead: "a brand new behaviour", text: "it was simply easier in Swift")
        let addedWhyNot = DirectEntry(
            lead: "a brand new behaviour",
            text: "**why not a plugin:** no EVENT carries pane attention state"
        )
        let addedHostNative = DirectEntry(
            lead: "a brand new behaviour",
            text: "**host-native core:** VISION requires the workspace to work with no plugins"
        )

        XCTAssertNil(
            Self.justificationDebt(for: existing, against: pinned),
            "An unchanged grandfathered entry owes nothing — that is what being pinned means."
        )
        XCTAssertEqual(
            Self.justificationDebt(for: grown, against: pinned),
            "grew from 40 to 80 characters",
            "Enlarging an entry is how this inventory actually grew; it must owe a justification."
        )
        XCTAssertEqual(
            Self.justificationDebt(for: addedBare, against: pinned),
            "is a new entry",
            "An unpinned lead is an addition and must owe a justification."
        )

        XCTAssertFalse(
            Self.carriesJustificationClause(addedBare),
            """
            "it was simply easier in Swift" must not read as a justification — convenience is \
            precisely what the clause exists to refuse.
            """
        )
        XCTAssertTrue(Self.carriesJustificationClause(addedWhyNot))
        XCTAssertTrue(Self.carriesJustificationClause(addedHostNative))
        XCTAssertFalse(
            Self.carriesJustificationClause(grown),
            "A grown entry with no clause is exactly the case the gate must catch."
        )
    }

    /// Why this entry owes a justification clause, or `nil` when it owes none.
    fileprivate static func justificationDebt(
        for entry: DirectEntry,
        against pinned: [String: Int]
    ) -> String? {
        guard let pinnedLength = pinned[entry.lead] else { return "is a new entry" }
        guard entry.length > pinnedLength else { return nil }
        return "grew from \(pinnedLength) to \(entry.length) characters"
    }

    fileprivate static func carriesJustificationClause(_ entry: DirectEntry) -> Bool {
        entry.text.contains("**why not a plugin:**")
            || entry.text.contains("**host-native core:**")
    }

    fileprivate static func unjustifiedMessage(entry: DirectEntry, reason: String) -> String {
        """
        DIRECT inventory entry "\(entry.lead)" \(reason) and carries no justification \
        clause. Add exactly one: "**why not a plugin:**" naming the specific missing \
        CONTRIBUTION, EVENT, or INTENT — the missing thing, not the difficulty — or \
        "**host-native core:**" citing the VISION requirement. Convenience, \
        familiarity, and "it was easier in Swift" are not justifications.
        """
    }
}

private extension DirectInventoryGateTests {
    struct DirectEntry {
        let lead: String
        let text: String

        var length: Int { text.count }
    }

    var packageRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    func lawText() throws -> String {
        let url = packageRoot
            .appendingPathComponent("docs/architecture-interaction-boundaries.md")
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// One block per column-0 `- `; two-space-indented lines continue the block; blank lines
    /// are skipped; the inventory ends at the next Markdown heading of any level. The block's
    /// lines are joined with single spaces and runs of whitespace collapse to one space, so
    /// reflowing a paragraph does not read as a change.
    func directInventoryEntries() throws -> [DirectEntry] {
        let lines = try lawText().components(separatedBy: "\n")
        guard let start = lines.firstIndex(where: { $0.hasPrefix("Current DIRECT inventory:") })
        else {
            XCTFail("The law no longer introduces its DIRECT inventory with a parseable heading line")
            return []
        }

        var blocks: [[String]] = []
        var current: [String]?
        var unclassified: [String] = []
        for line in lines[(start + 1)...] {
            if line.hasPrefix("#") { break }
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { continue }
            if line.hasPrefix("- ") {
                if let block = current { blocks.append(block) }
                current = [String(line.dropFirst(2))]
            } else if line.hasPrefix("  "), current != nil {
                current?.append(trimmed)
            } else {
                // Anything else used to fall through this `else` into nothing, which made
                // the gate blind exactly where it must not be: a DIRECT behaviour written
                // as a column-0 paragraph, a tab-indented continuation, or a fenced block
                // was invisible to BOTH the count pin and the length pin, so it could be
                // added with no gate firing at all. A parser that cannot classify a line
                // must say so rather than quietly shrink what it guards.
                unclassified.append(trimmed)
            }
        }
        if let block = current { blocks.append(block) }

        XCTAssertEqual(
            unclassified,
            [],
            """
            The DIRECT inventory contains lines this gate cannot classify, so they are \
            pinned by nothing. Every line between "Current DIRECT inventory:" and the next \
            heading must be a column-0 "- " entry or a two-space-indented continuation of \
            one. Reformat the content, or teach this parser the shape deliberately — do \
            not leave it unread.
            """
        )

        return blocks.map { block in
            let text = block
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .joined(separator: " ")
                .split(whereSeparator: { $0.isWhitespace })
                .joined(separator: " ")
            let lead: String
            if let boundary = text.firstIndex(where: { $0 == ":" || $0 == ";" }) {
                lead = String(text[text.startIndex ..< boundary])
            } else {
                lead = text
            }
            return DirectEntry(lead: lead, text: text)
        }
    }

    func shippedPluginCount() throws -> Int {
        let root = packageRoot.appendingPathComponent("plugins", isDirectory: true)
        let entries = try FileManager.default.contentsOfDirectory(
            at: root,
            includingPropertiesForKeys: [.isDirectoryKey]
        )
        return entries.filter { url in
            FileManager.default.fileExists(
                atPath: url.appendingPathComponent("manifest.json").path
            )
        }.count
    }

    static func firstCapturedInteger(in text: String, pattern: String) -> Int? {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return nil }
        let range = NSRange(text.startIndex ..< text.endIndex, in: text)
        guard
            let match = regex.firstMatch(in: text, range: range),
            match.numberOfRanges > 1,
            let captured = Range(match.range(at: 1), in: text)
        else { return nil }
        return Int(text[captured])
    }
}
